# Generated by Django 2.0.7 on 2018-07-25 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('montant', models.DecimalField(decimal_places=5, max_digits=19)),
            ],
            options={
                'verbose_name': 'annonces',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Annonceur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_web', models.URLField(blank=True)),
                ('phone', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'annonceur',
            },
        ),
        migrations.AddField(
            model_name='annonces',
            name='annonceur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.Annonceur'),
        ),
    ]
